#TO DO = Define the Provider
#TO DO = Define Availability Zone
#TO DO = Define VPC and Subnets
#TO DO = Define Internate Gateway
#TO DO = Define Network Gateway
#TO DO = Define Elastic IP
#TO DO = Define Route Tables
#TO DO = Associate Route tables with Subnets
#TO DO = Define Security Groups
#TO DO = Create Bastion VM
#TO DO = Define Security Group for Bastion
#TO DO = Define Auto Scaling Group
#TO DO = Define Scaling Policies
#TO DO = Define Launch Configuration
#TO DO = Configuration  for NLB
#TO DO = Target group for ALB
#TO DO = Define Internal Security Group
